export { default as Home } from "./Home";
export { default as MainPage } from "./main-page";
export { default as Hodimlar } from "./Hodimlar";
export { default as YolUstalari } from "./YolUstalari";
export { default as Jadval } from "./Jadval";
export { default as Kuzatuv } from "./Kuzatuv";
export { default as Asboblar } from "./Asboblar";
export { default as Manzil } from "./Manzil";
export { default as Login } from "./Login";
